// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// IMPORTANT: Replace these placeholder values with your actual Firebase project configuration.
/// Run 'flutterfire configure' to generate the correct configuration for your project.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6orgXMVZbObpkaY9igkYsDbU9SBUUjTY',
    appId: '1:217588531616:web:ca4445c228616c8c7364c5',
    messagingSenderId: '217588531616',
    projectId: 'nexus-ccef7',
    authDomain: 'nexus-ccef7.firebaseapp.com',
    storageBucket: 'nexus-ccef7.firebasestorage.app',
    measurementId: 'G-PG3E6GH9FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSrv4g36SqfbiXaovxkIyBHf6SUNhSH5A',
    appId: '1:217588531616:android:07b4c36553187dc67364c5',
    messagingSenderId: '217588531616',
    projectId: 'nexus-ccef7',
    storageBucket: 'nexus-ccef7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtIcfXQZjou8DBeWA4dvcDj6fAX8JPVX0',
    appId: '1:217588531616:ios:b0df47e844c3b9667364c5',
    messagingSenderId: '217588531616',
    projectId: 'nexus-ccef7',
    storageBucket: 'nexus-ccef7.firebasestorage.app',
    androidClientId: '217588531616-ne81iuvd5kletf1cqduf53050c6mfhl3.apps.googleusercontent.com',
    iosClientId: '217588531616-3kl1rr4gvt6avgdl66g2nakurnvimatc.apps.googleusercontent.com',
    iosBundleId: 'com.mahanadhi.nexusTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtIcfXQZjou8DBeWA4dvcDj6fAX8JPVX0',
    appId: '1:217588531616:ios:b0df47e844c3b9667364c5',
    messagingSenderId: '217588531616',
    projectId: 'nexus-ccef7',
    storageBucket: 'nexus-ccef7.firebasestorage.app',
    androidClientId: '217588531616-ne81iuvd5kletf1cqduf53050c6mfhl3.apps.googleusercontent.com',
    iosClientId: '217588531616-3kl1rr4gvt6avgdl66g2nakurnvimatc.apps.googleusercontent.com',
    iosBundleId: 'com.mahanadhi.nexusTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6orgXMVZbObpkaY9igkYsDbU9SBUUjTY',
    appId: '1:217588531616:web:089e8d6c30acf6347364c5',
    messagingSenderId: '217588531616',
    projectId: 'nexus-ccef7',
    authDomain: 'nexus-ccef7.firebaseapp.com',
    storageBucket: 'nexus-ccef7.firebasestorage.app',
    measurementId: 'G-0CYL9L9GQ9',
  );

}